### ISSUE TITLE
MacOS 11.1

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [aa15032261/apple_set_os-loader#2]
I have Macbook Pro 16″ 2019 with Intel Core i9-9980HK CPU and AMD Radeon Pro 5500M 8GB GPU. This model has T2 chip.

It has MacOS 11.1 and Windows 10 Pro 64-bit installed via Bootcamp.

@aa15032261 Is it possible to enable integrated Intel UHD Graphics 630 on Windows 10 using this tool?

**Comment by Naozumi520** [comment]
Yes, It can.
![image](https://user-images.githubusercontent.com/52615455/115118623-f3229380-9f58-11eb-99c7-79e759eaa71a.png)

**Comment by Ahmed97i** [comment]
@FluorescentHallucinogen please can you inform me if you have enabled your igpu because when I enable it I cannot use my dgpu it says windows disabled the device(amd dgpu) with error code 43

**Comment by jadenquinn** [comment]
I wonder this as well. I'm on the exact same hardware.

**Comment by FluorescentHallucinogen** [comment]
@Ahmed97i @jadenquinn Sorry for such a long delay. Yes, I managed to enable both the integrated GPU and the discrete GPU at the same time. Both are working.

Moreover, this works even with the latest version of macOS Tahoe 26.4.1.
