### ISSUE TITLE
The makefile doesn't work.

### ISSUE THREAD

**Issue by jadenquinn** [aa15032261/apple_set_os-loader#5]
Jadens-MacBook-Pro:~ jadeny$ cd /Users/jaden_1/Downloads/apple_set_os-loader-master 
Jadens-MacBook-Pro:apple_set_os-loader-master jadeny$ make
cc -I/usr/include/efi -I/usr/include/efi/x86_64 -DGNU_EFI_USE_MS_ABI -fPIC -fshort-wchar -ffreestanding -fno-stack-protector -maccumulate-outgoing-args -Wall -Dx86_64 -Werror -m64 -mno-red-zone   -c -o lib/int_event.o lib/int_event.c
clang: error: unknown argument: '-maccumulate-outgoing-args'
make: *** [lib/int_event.o] Error 1
Jadens-MacBook-Pro:apple_set_os-loader-master jadeny$

**Comment by aa15032261** [comment]
It should build correctly in docker.
